version: '3'
services:
  db:
    image: mysql:8.0.32
    ports:
      - "32000:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/:ro
      
  catalogue_ms:
    build: ./backend/catalogue_ms
    ports:
      - "5000:5000"
    depends_on:
      - db

  login_ms:
    build: ./backend/login_ms
    ports:
      - "5001:5001"
    depends_on:
      - db

  login:
    build: ./backend/login
    ports:
      - "7000:7000"

  
    

  frontend:
    build: ./frontend/frontend-app 
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend/frontend-app:/user/src/app
    


volumes: 
  db:
    driver: local