# Generated by Django 4.1.7 on 2023-03-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptio',
            new_name='description',
        ),
    ]
